language: android
android:
  components:
    - build-tools-20.0.0
    - android-19
before_install:
    - export projectdir=$(pwd)
    # newer version of gradle
    - wget http://services.gradle.org/distributions/gradle-2.2.1-bin.zip
    - unzip -qq gradle-2.2.1-bin.zip
    - export GRADLE_HOME=$PWD/gradle-2.2.1
    - export PATH=$GRADLE_HOME/bin:$PATH
    - echo $GRADLE_HOME
    - echo $ANDROID_HOME
    - echo "sdk.dir=$ANDROID_HOME" > local.properties
    # local dependency
    - cd ..
    - git clone https://github.com/Pozo/dex-jar.git
    - cd dex-jar
    - mvn clean package install:install-file -Dfile=target/dex-jar-1.0.jar -DgroupId=com.epam.android -DartifactId=dex-jar -Dversion=1.0 -Dpackaging=jar
script:
    - cd $projectdir
    - gradle build connectedCheck
